AAP-89910 AAP-89949 AAP-89827 Update all backend dependencies (#270)
* Update all BE deps

To update all deps:
 rm requirements-build.txt
 make sync-requirements

AAP-89910
AAP-89949
AAP-89827

Signed-off-by: Justin Cinkelj <justin.cinkelj@xlab.si>

* Fix: Regenerate requirements-build.txt with pip-tools 7.6.1

The CI uses pip-tools 7.6.1 which adds --no-index to the header comment.
Regenerated with a clean venv to match CI expectations.

* Upgrade django-weasyprint to 2.5.0 for weasyprint 70.0 compatibility

django-weasyprint 2.4.0 is incompatible with weasyprint 70.0 due to
removed default_url_fetcher attribute. Version 2.5.0 implements the
new URLFetcher API compatible with weasyprint 68+.

Fixes test failure: AttributeError: module 'weasyprint' has no attribute 'default_url_fetcher'

* Regenerate requirements with django-weasyprint 2.5.0

---------

Signed-off-by: Justin Cinkelj <justin.cinkelj@xlab.si>