Update rpm lock file, and script to generate updates
nginx was not installable:
 Problem: package nginx-2:1.20.1-22.el9_6.3.x86_64 from ubi-9-for-x86_64-appstream-rpms requires systemd, but none of the providers can be installed
  - conflicting requests
  - nothing provides systemd-libs = 252-55.el9_7.7 needed by systemd-252-55.el9_7.7.x86_64 from ubi-9-for-x86_64-baseos-rpms

Podman "security-opt label=disable" is added, to fix:
 PermissionError: [Errno 13] Permission denied: '/data/rpms.in.yaml'

Signed-off-by: Justin Cinkelj <justin.cinkelj@xlab.si>